[package]
name = "crust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
colored = "2.0.0"
rustyline = { version = "9.0.0", optional = true }

[features]
default = ["readline"]
readline = ["rustyline"]
