[package]
name = "crusty"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = { version = "9.0.0", optional = true }
term = "0.6.0"

[features]
readline = ["rustyline"]
